"""
Unit tests for parameter_descriptions: the defaults, aliases, coercions and
finalize steps every test's parameters go through.

Pure functions are called directly; anything that depends on the order the
pipeline runs in (defaults computed from other parameters, deprecated
aliases, file discovery) is driven through parse_string() the way a real
tests.txt is.
"""

import os
import re
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

import parameter_descriptions as pd  # noqa: E402
from parameter_descriptions import (  # noqa: E402
    PARAMETER_LIST,
    PARAMETERS,
    Parameter,
    check_valid_parameter_name,
    finalize_command,
    finalize_compile_commands,
    finalize_compiler_checker_list,
    finalize_max_bytes,
    finalize_parallel_tests,
    heuristically_default_files,
    heuristically_infer_program,
    print_markdown,
    search_path,
    select_command_from_alternatives,
)
from parse_test_specification import parse_string  # noqa: E402
from util import TestSpecificationError as SpecificationError  # noqa: E402


@pytest.fixture
def supplied(tmp_path):
    """a supplied_files_directory holding files a spec can refer to"""
    (tmp_path / "one").write_text("1\n")
    (tmp_path / "two").write_text("2\n")
    return tmp_path


def parse(specification, supplied_files_directory=".", **initial):
    initial["supplied_files_directory"] = str(supplied_files_directory)
    tests, _ = parse_string(specification, initial_parameters=initial)
    return tests


def parse_error(specification, supplied_files_directory="."):
    with pytest.raises(SpecificationError) as info:
        parse(specification, supplied_files_directory)
    return str(info.value)


def single_test(specification, supplied_files_directory=".", **initial):
    """the parameters of the single test 't' in specification"""
    return parse(specification, supplied_files_directory, **initial)["t"]


# Parameter objects and their documentation


@pytest.mark.parametrize(
    "default,required_type",
    [
        (1, int),
        (True, bool),
        (1.5, float),
        ("s", str),
        ([], list),
        ({}, None),
        (None, None),
    ],
)
def test_required_type_is_inferred_from_a_simple_default(default, required_type):
    assert Parameter("x", default=default).required_type is required_type


def test_explicit_required_type_wins_over_the_default_type():
    assert Parameter("x", default=1, required_type=str).required_type is str


def test_get_default_calls_a_callable_default_with_the_parameters():
    assert Parameter("x", default=lambda p: p["y"] * 2).get_default({"y": 21}) == 42
    assert Parameter("x", default=7).get_default({}) == 7


def test_description_markdown_shows_a_constant_default_with_escaped_brackets():
    markdown = PARAMETERS["arguments"].description_markdown()
    assert markdown.startswith("**`arguments`** = \\[\\]\n\n")
    assert "Command-line arguments for this test." in markdown


def test_description_markdown_omits_a_computed_default():
    markdown = PARAMETERS["program"].description_markdown()
    assert markdown.startswith("**`program`**\n\n")
    assert " = " not in markdown.splitlines()[0]


def test_description_markdown_dedents_and_turns_br_into_line_breaks():
    p = Parameter("x", description="    first<br>\n    second\n")
    assert p.description_markdown() == "**`x`**\n\nfirst  \nsecond\n"


def test_print_markdown_lists_each_documented_parameter_once_and_no_hidden_ones(capsys):
    print_markdown()
    lines = capsys.readouterr().out.splitlines()
    assert lines[0] == "<!--- start - autogenerated from parameter_descriptions.py --->"
    assert lines[-1] == "<!--- end - autogenerated from parameter_descriptions.py --->"
    headers = [re.fullmatch(r"\*\*`(\w+)`\*\*( = .*)?", line) for line in lines]
    documented = [m.group(1) for m in headers if m]
    for p in PARAMETER_LIST:
        if isinstance(p, Parameter):
            assert documented.count(p.name) == (
                1 if p.show_in_documentation else 0
            ), p.name
    assert "### Parameters specifying command to be run" in lines


# heuristics for program and files


@pytest.mark.parametrize(
    "parameters,program",
    [
        ({"command": ["./prog", "x"], "files": ["prog.c"]}, "prog"),
        ({"command": "./prog x", "files": ["prog.c"]}, "prog"),
        ({"command": "python3 prog.py", "files": ["prog.py"]}, "prog.py"),
        ({"command": "./prog x", "files": []}, "prog"),
        ({"command": "./a-b", "files": []}, "a-b"),
        ({"command": "cat", "files": [], "compiler_args": ["-o", "cat"]}, "cat"),
        ({"command": "", "files": ["Hello.C", "b.c"]}, "Hello"),
        ({"command": "", "files": "single.cc"}, "single"),
        ({"command": "", "files": ["prog.h"]}, "prog"),
        ({"command": "", "files": ["prog.py"]}, "prog.py"),
        ({"command": "ls -l", "files": []}, "ls"),
        ({"command": "/bin/ls -l", "files": []}, "ls"),
        ({"label": "test_1_2"}, "test"),
        ({}, ""),
    ],
)
def test_program_is_inferred_from_command_files_or_label(parameters, program):
    parameters.setdefault("compiler_args", [])
    assert heuristically_infer_program(parameters) == program


@pytest.mark.parametrize(
    "program,files",
    [("prog", ["prog.c"]), ("prog.sh", ["prog.sh"]), ("", [])],
)
def test_files_default_to_program_with_c_appended_unless_it_has_a_suffix(
    program, files
):
    assert heuristically_default_files({"program": program}) == files


# commands


def test_command_list_elements_are_stringified():
    assert finalize_command("command", ["a", 1], {}) == ["a", "1"]


def test_command_string_and_none_are_kept_or_emptied():
    assert finalize_command("command", "a b", {}) == "a b"
    assert finalize_command("command", None, {}) == []


def test_deprecated_shell_flag_joins_a_list_command_into_a_shell_string():
    assert finalize_command("command", ["a", 1], {"shell": True}) == "a 1"
    assert (
        finalize_command("setup_command", ["a", "b"], {"setup_command_shell": "1"})
        == "a b"
    )
    assert finalize_command(
        "setup_command", ["a", "b"], {"setup_command_shell": False}
    ) == ["a", "b"]


def test_command_of_the_wrong_type_is_an_error_naming_the_parameter():
    with pytest.raises(
        SpecificationError, match="invalid value for parameter 'command': 5"
    ):
        finalize_command("command", 5, {})


def test_deprecated_shell_flags_work_through_the_pipeline():
    t = single_test(
        "files=a.c\nt command=['./a', 1] shell=1 setup_command=['x', 'y'] "
        "setup_command_shell=1 pre_compile_command=['p'] pre_compile_command_shell=0\n"
    )
    assert t["command"] == "./a 1"
    assert t["setup_command"] == "x y"
    assert t["pre_compile_command"] == ["p"]


def test_bytes_command_is_rejected_with_line_prefix():
    assert parse_error("files=a.c\nt command=b'x'\n") == (
        "<string>:2: invalid value for parameter 'command': b'x'"
    )


# compilers and checkers


def compiler_parameters(files, program="x"):
    return {
        "files": files,
        "program": program,
        "default_checkers": PARAMETERS["default_checkers"].default,
        "default_compilers": PARAMETERS["default_compilers"].default,
    }


def test_unset_checkers_default_by_suffix_of_the_first_file():
    assert finalize_compiler_checker_list(
        "checkers", None, compiler_parameters(["x.py"])
    ) == [["python3", "-B", "-m", "py_compile"]]


def test_unset_compilers_default_by_suffix_of_the_first_file():
    assert finalize_compiler_checker_list(
        "compilers", None, compiler_parameters(["x.rs"])
    ) == [["rustc"]]


@pytest.mark.parametrize("files", [["x.unknown"], ["Makefile"], []])
def test_unknown_suffix_or_no_files_gives_no_compilers(files):
    assert (
        finalize_compiler_checker_list("compilers", None, compiler_parameters(files))
        == []
    )


def test_colon_separated_string_is_split_into_commands_for_backwards_compatibility():
    assert finalize_compiler_checker_list(
        "compilers", "gcc -Wall:clang -o %", compiler_parameters([])
    ) == [
        ["gcc", "-Wall"],
        ["clang", "-o", "%"],
    ]


def test_percent_is_replaced_by_program_in_list_commands_only():
    assert finalize_compiler_checker_list(
        "compilers", ["gcc -o %", ["clang", "-o", "%", 1]], compiler_parameters([])
    ) == ["gcc -o %", ["clang", "-o", "x", "1"]]


@pytest.mark.parametrize("value", [5, [[]], [""], [5], {"a": 1}])
def test_invalid_compiler_values_are_errors_naming_the_parameter(value):
    with pytest.raises(
        SpecificationError, match="invalid value for parameter 'compilers'"
    ):
        finalize_compiler_checker_list("compilers", value, compiler_parameters([]))


@pytest.fixture
def fake_path(tmp_path, monkeypatch):
    """a PATH holding only an executable 'mycc' and a non-executable 'notexec'"""
    bindir = tmp_path / "bin"
    bindir.mkdir()
    (bindir / "mycc").write_text("#!/bin/sh\n")
    (bindir / "mycc").chmod(0o755)
    (bindir / "notexec").write_text("#!/bin/sh\n")
    (bindir / "notexec").chmod(0o644)
    (bindir / "adir").mkdir()
    monkeypatch.setenv("PATH", str(bindir))
    return bindir


def test_search_path_finds_only_executable_files(fake_path):
    assert search_path("mycc") == str(fake_path / "mycc")
    assert search_path("notexec") is None
    assert search_path("adir") is None
    assert search_path("missing") is None


def test_first_alternative_found_on_path_is_chosen(fake_path):
    alternatives = [["missing"], "notexec -x", ["mycc", "-Wall"], ["mycc"]]
    assert select_command_from_alternatives(alternatives) == ["mycc", "-Wall"]
    assert select_command_from_alternatives(["mycc -Wall", ["mycc"]]) == "mycc -Wall"


@pytest.mark.parametrize(
    "alternatives", [[], [["missing"]], [[], ["mycc"]], [5, ["mycc"]]]
)
def test_no_usable_alternative_gives_none(fake_path, alternatives):
    assert select_command_from_alternatives(alternatives) is None


def test_alternatives_inside_a_compiler_list_pick_the_first_on_path(fake_path):
    value = [[["missing"], ["mycc", "-o", "%"]], ["other"]]
    assert finalize_compiler_checker_list(
        "compilers", value, compiler_parameters([])
    ) == [
        ["mycc", "-o", "x"],
        ["other"],
    ]


def test_no_alternative_on_path_is_an_error_naming_the_parameter(fake_path):
    with pytest.raises(
        SpecificationError, match="parameter 'compilers' no alternative found"
    ):
        finalize_compiler_checker_list(
            "compilers", [[["missing"]]], compiler_parameters([])
        )


def test_default_c_compilers_choose_an_alternative_on_path(fake_path):
    (fake_path / "clang").write_text("#!/bin/sh\n")
    (fake_path / "clang").chmod(0o755)
    t = single_test("files=a.c\nt command=./a\n")
    assert t["compilers"] == [["clang", "-Wall"]]
    assert t["compile_commands"] == [["clang", "-Wall", "-o", "a"]]


def test_compile_commands_string_and_list_are_used_as_given():
    assert finalize_compile_commands("compile_commands", "gcc -o a a.c", {}) == [
        "gcc -o a a.c"
    ]
    assert finalize_compile_commands(
        "compile_commands", [["gcc", 1], "clang x"], {}
    ) == [
        ["gcc", "1"],
        "clang x",
    ]


def compile_commands(compilers, compiler_args=None, program="a"):
    return finalize_compile_commands(
        "compile_commands",
        None,
        {
            "compilers": compilers,
            "compiler_args": compiler_args or [],
            "program": program,
        },
    )


def test_c_compile_without_dash_o_gets_output_named_after_program():
    assert compile_commands([["gcc", "-Wall"]]) == [["gcc", "-Wall", "-o", "a"]]
    assert compile_commands(["gcc -Wall"]) == ["gcc -Wall -o a"]
    assert compile_commands([["dcc"], ["clang"]]) == [
        ["dcc", "-o", "a"],
        ["clang", "-o", "a"],
    ]


def test_c_compile_already_naming_output_or_program_is_left_alone():
    assert compile_commands([["gcc", "-Wall", "-o", "a"]]) == [
        ["gcc", "-Wall", "-o", "a"]
    ]
    assert compile_commands([["gcc", "-Wall", "a"]]) == [["gcc", "-Wall", "a"]]
    assert compile_commands(["gcc -Wall -o a"]) == ["gcc -Wall -o a"]


def test_duplicate_dash_o_from_compiler_args_replaces_the_compilers_one():
    assert compile_commands([["gcc", "-o", "a"]], ["-o", "b", "a.c"]) == [
        ["gcc", "-o", "b", "a.c"]
    ]
    # a string compiler is turned into a list when its -o is removed
    assert compile_commands(["gcc -o a"], ["-o", "b"]) == [["gcc", "-o", "b"]]


def test_compiler_args_are_appended_to_every_compiler():
    assert compile_commands([["gcc", "-Wall"]], ["-o", "b"]) == [
        ["gcc", "-Wall", "-o", "b"]
    ]
    assert compile_commands([["gcc", "-o", "a"]], ["a.c"]) == [
        ["gcc", "-o", "a", "a.c"]
    ]
    assert compile_commands([["javac"]], ["-g"]) == [["javac", "-g"]]


def test_non_c_compilers_get_no_dash_o():
    assert compile_commands([["javac"]]) == [["javac"]]


def test_compile_commands_via_the_pipeline_from_compilers_and_compiler_args():
    t = single_test(
        "files=a.c\nt command=./a compilers=[['gcc','-Wall']] compiler_args=['-o','b','a.c']\n"
    )
    assert t["compile_commands"] == [["gcc", "-Wall", "-o", "b", "a.c"]]
    t = single_test("files=a.c\nt command=./a compilers='gcc -Wall:clang -Wall'\n")
    assert t["compile_commands"] == [
        ["gcc", "-Wall", "-o", "a"],
        ["clang", "-Wall", "-o", "a"],
    ]
    # only compilers whose name contains "cc" or "clang" get the -o convenience
    t = single_test("files=a.cc\nt command=./a\n")
    assert t["compile_commands"] == [["g++", "-Wall"]]


def test_percent_in_compiler_args_is_replaced_by_program():
    t = single_test(
        "files=a.c\nt command=./a compilers=[['gcc']] compiler_args=['-o','%']\n"
    )
    assert t["compile_commands"] == [["gcc", "-o", "a"]]


# stdin, expected output and files


def test_stream_string_is_used_as_is(supplied):
    t = single_test(
        "files=a.c\nt command=./a stdin='in\\n' expected_stdout=out\n", supplied
    )
    assert t["stdin"] == "in\n"
    assert t["expected_stdout"] == "out"
    assert t["expected_stderr"] == ""


def test_stream_list_of_files_is_concatenated_from_supplied_files_directory(supplied):
    t = single_test(
        "files=a.c\nt command=./a stdin=['one','two'] expected_stdout=['one']\n",
        supplied,
    )
    assert t["stdin"] == "1\n2\n"
    assert t["expected_stdout"] == "1\n"


def test_absolute_pathnames_in_a_stream_list_are_not_relative_to_supplied_files(
    supplied, tmp_path
):
    elsewhere = tmp_path / "elsewhere.txt"
    elsewhere.write_text("E\n")
    t = single_test(
        f"files=a.c\nt command=./a stdin=[{str(elsewhere)!r}]\n",
        supplied / "missing_dir",
    )
    assert t["stdin"] == "E\n"


def test_deprecated_file_parameters_supply_the_streams(supplied):
    t = single_test(
        "files=a.c\nt command=./a stdin_file=one expected_stdout_file=two expected_stderr_file=one\n",
        supplied,
    )
    assert (t["stdin"], t["expected_stdout"], t["expected_stderr"]) == (
        "1\n",
        "2\n",
        "1\n",
    )


def test_files_named_after_the_label_supply_unset_streams(supplied):
    (supplied / "t.stdin").write_text("in\n")
    (supplied / "t.stdout").write_text("out\n")
    (supplied / "t.stderr").write_text("err\n")
    t = single_test("files=a.c\nt command=./a\n", supplied)
    assert (t["stdin"], t["expected_stdout"], t["expected_stderr"]) == (
        "in\n",
        "out\n",
        "err\n",
    )
    u = parse("files=a.c\nu command=./a\n", supplied)["u"]
    assert (u["stdin"], u["expected_stdout"], u["expected_stderr"]) == ("", "", "")


def test_explicit_stream_wins_over_a_file_named_after_the_label(supplied):
    (supplied / "t.stdin").write_text("in\n")
    t = single_test("files=a.c\nt command=./a stdin=explicit\n", supplied)
    assert t["stdin"] == "explicit"


def test_missing_stream_file_is_an_error_naming_the_pathname(supplied):
    message = parse_error("files=a.c\nt command=./a stdin=['missing']\n", supplied)
    assert message.startswith("<string>:2: ")
    assert str(supplied / "missing") in message


@pytest.mark.parametrize("value", ["[[1]]", "{'a': 1}"])
def test_stream_of_the_wrong_type_is_an_error(supplied, value):
    assert parse_error(f"files=a.c\nt command=./a stdin={value}\n", supplied) == (
        "<string>:2: invalid type for value in stdin"
    )


def test_empty_stream_list_is_an_empty_stream(supplied):
    assert single_test("files=a.c\nt command=./a stdin=[]\n", supplied)["stdin"] == ""


def test_expected_file_name_and_contents_become_an_expected_files_entry(supplied):
    t = single_test(
        "files=a.c\nt command=./a expected_file_name=out.txt expected_file_contents=hello\n",
        supplied,
    )
    assert t["expected_files"] == {"out.txt": "hello"}


def test_expected_file_contents_default_to_the_label_expected_file(supplied):
    (supplied / "t.expected_file").write_text("filecontents\n")
    t = single_test("files=a.c\nt command=./a expected_file_name=out.txt\n", supplied)
    assert t["expected_files"] == {"out.txt": "filecontents\n"}
    u = parse("files=a.c\nu command=./a expected_file_name=out.txt\n", supplied)["u"]
    assert u["expected_files"] == {"out.txt": ""}


def test_expected_files_values_may_be_strings_or_lists_of_files(supplied):
    t = single_test(
        "files=a.c\nt command=./a expected_files={'a.txt': 'x', 'b.txt': ['one', 'two']}\n",
        supplied,
    )
    assert t["expected_files"] == {"a.txt": "x", "b.txt": "1\n2\n"}


@pytest.mark.parametrize(
    "value,message",
    [
        ("[1]", "error invalid value for parameter 'expected_files': [1]"),
        ("{1: 'x'}", "error invalid type for parameter 'expected_files' key: 1"),
        ("{'x': 5}", "invalid type for value in expected_files"),
    ],
)
def test_invalid_expected_files_are_errors(supplied, value, message):
    assert (
        parse_error(f"files=a.c\nt command=./a expected_files={value}\n", supplied)
        == f"<string>:2: {message}"
    )


# output limits


@pytest.mark.parametrize(
    "expected_length,limit",
    [(0, 10000), (2000, 20000), (2000000, 10000000), (6000000, 12000000)],
)
def test_unset_max_bytes_is_computed_from_the_expected_length(expected_length, limit):
    assert (
        finalize_max_bytes(
            "max_stdout_bytes", None, {"expected_stdout": "x" * expected_length}
        )
        == limit
    )


def test_explicit_max_bytes_is_never_below_the_expected_length():
    assert (
        finalize_max_bytes("max_stdout_bytes", 5, {"expected_stdout": "x" * 100}) == 100
    )
    assert (
        finalize_max_bytes("max_stderr_bytes", "500", {"expected_stderr": "x" * 100})
        == 500
    )
    assert finalize_max_bytes("max_stderr_bytes", 0, {}) == 0


# dcc output checking


def dcc(specification):
    t = single_test(specification)
    return t["dcc_output_checking"], {
        k: v for k, v in t["environment"].items() if k.startswith("DCC_")
    }


def test_dcc_output_checking_is_enabled_for_a_simple_c_test_and_sets_dcc_variables():
    enabled, variables = dcc("files=a.c\nt command=./a expected_stdout=hi\n")
    assert enabled is True
    assert variables == {
        "DCC_EXPECTED_STDOUT": "hi",
        "DCC_IGNORE_CASE": "False",
        "DCC_COMPARE_ONLY_CHARACTERS": "",
        "DCC_IGNORE_CHARACTERS": "",
        "DCC_IGNORE_TRAILING_WHITE_SPACE": "True",
        "DCC_IGNORE_WHITE_SPACE": "False",
        "DCC_IGNORE_BLANK_LINES": "False",
        "DCC_MAX_STDOUT_BYTES": "10000",
    }


def test_dcc_variables_reflect_comparison_parameters():
    _, variables = dcc(
        "files=a.c\nt command=./a expected_stdout=hi ignore_whitespace=1 ignore_case=1 compare_only_characters=abc\n"
    )
    assert variables["DCC_IGNORE_CASE"] == "True"
    assert variables["DCC_IGNORE_WHITE_SPACE"] == "True"
    assert variables["DCC_COMPARE_ONLY_CHARACTERS"] == "abc"
    assert set(variables["DCC_IGNORE_CHARACTERS"]) == set(" \t\r\x0b\x0c")


@pytest.mark.parametrize("value", ["0", "no", "''"])
def test_dcc_output_checking_can_be_disabled(value):
    assert dcc(
        f"files=a.c\nt command=./a expected_stdout=hi dcc_output_checking={value}\n"
    ) == (False, {})


@pytest.mark.parametrize("value", ["auto", "1", "yes"])
def test_dcc_output_checking_auto_or_forced_is_enabled_for_a_simple_test(value):
    assert (
        dcc(
            f"files=a.c\nt command=./a expected_stdout=hi dcc_output_checking={value}\n"
        )[0]
        is True
    )


def test_forced_dcc_output_checking_ignores_the_auto_conditions():
    assert (
        dcc(
            "files=a.c\nt command=./a expected_stdout=hi dcc_output_checking=1 expected_stderr=e\n"
        )[0]
        is True
    )


@pytest.mark.parametrize(
    "specification",
    [
        "files=a.c\nt command=./a expected_stdout=hi expected_stderr=e\n",
        "files=['a.c','b.c']\nt command=./a expected_stdout=hi\n",
        "files=a.py\nt command=./a expected_stdout=hi\n",
        "files=a.c\nt command='./a | cat' expected_stdout=hi\n",
        "files=a.c\nt command=./a expected_stdout=hi compiler_args=-lm\n",
        "files=a.c\nt command=./a expected_stdout=hi postprocess_output_command=cat\n",
    ],
)
def test_dcc_output_checking_auto_is_disabled_for_complex_tests(specification):
    assert dcc(specification) == (False, {})


def test_shell_command_without_metacharacters_keeps_dcc_output_checking():
    assert dcc("files=a.c\nt command='./a x' expected_stdout=hi\n")[0] is True


# environment


def test_environment_keeps_only_variables_matching_environment_kept(monkeypatch):
    monkeypatch.setenv("UNWANTED_VARIABLE", "junk")
    monkeypatch.setenv("LANG", "C.UTF-8")
    monkeypatch.setenv("LOGNAME", "someone")
    t = single_test("files=a.c\nt command=./a\n")
    assert t["__environment_original"]["UNWANTED_VARIABLE"] == "junk"
    assert "UNWANTED_VARIABLE" not in t["__environment_filtered"]
    assert "UNWANTED_VARIABLE" not in t["environment"]
    assert t["environment"]["LANG"] == "C.UTF-8"
    assert t["environment"]["LOGNAME"] == "someone"


def test_environment_base_sets_home_locale_and_path_with_dot_last(monkeypatch):
    monkeypatch.setenv("PATH", "/opt/bin")
    t = single_test("files=a.py\nt command=./a.py\n")
    assert t["environment"]["HOME"] == "."
    assert t["environment"]["LC_COLLATE"] == "POSIX"
    assert t["environment"]["LC_NUMERIC"] == "POSIX"
    assert t["environment"]["PERL5LIB"] == "."
    assert t["environment"]["PATH"] == "/bin:/usr/bin:/usr/local/bin:/opt/bin:."


def test_environment_kept_regex_must_match_the_whole_name(monkeypatch):
    monkeypatch.setenv("SAMPLE_ENVIRONMENT_VARIABLE", "sample_value")
    monkeypatch.setenv("LANG", "C.UTF-8")
    t = single_test("files=a.c\nt command=./a environment_kept='SAMPLE_.*'\n")
    assert t["environment"]["SAMPLE_ENVIRONMENT_VARIABLE"] == "sample_value"
    assert "LANG" not in t["environment"]
    t = single_test("files=a.c\nt command=./a environment_kept='SAMPLE'\n")
    assert "SAMPLE_ENVIRONMENT_VARIABLE" not in t["environment"]


def test_environment_set_values_are_stringified_and_override_the_base():
    t = single_test(
        "files=a.c\nt command=./a environment_set={'answer': 42, 'HOME': '/h'}\n"
    )
    assert t["environment_set"] == {"answer": "42", "HOME": "/h"}
    assert t["environment"]["answer"] == "42"
    assert t["environment"]["HOME"] == "/h"


def test_explicit_environment_base_replaces_the_default_base(monkeypatch):
    monkeypatch.setenv("LANG", "C.UTF-8")
    t = single_test("files=a.c\nt command=./a environment_base={'ONLY': 1}\n")
    assert t["environment_base"] == {"ONLY": "1"}
    assert t["environment"]["ONLY"] == "1"
    assert t["environment"]["LANG"] == "C.UTF-8"
    assert "HOME" not in t["environment"]


def test_explicit_environment_replaces_everything_but_dcc_variables():
    t = single_test("files=a.c\nt command=./a environment={'X': 1}\n")
    assert {k: v for k, v in t["environment"].items() if not k.startswith("DCC_")} == {
        "X": "1"
    }


def test_environment_of_the_wrong_type_is_an_error():
    assert parse_error("files=a.c\nt command=./a environment=x\n") == (
        "<string>:2: invalid value for parameter 'environment': x"
    )


def test_environment_set_of_the_wrong_type_is_an_error_naming_the_parameter():
    assert "parameter 'environment_set'" in parse_error(
        "files=a.c\nt command=./a environment_set=[1]\n"
    )


# aliases


@pytest.mark.parametrize(
    "alias,parameter,value,expected",
    [
        ("cpu", "max_cpu_seconds", "3", 3),
        ("max_cpu", "max_cpu_seconds", "2", 2),
        ("timeout", "max_real_seconds", "9", 9),
        ("max_wall_clock", "max_real_seconds", "7", 7),
        ("ignore_white_space", "ignore_whitespace", "1", True),
        ("ignore_trailing_white_space", "ignore_trailing_whitespace", "0", False),
        ("prediff_filter", "postprocess_output_command", "cat", "cat"),
        ("post_process_output_command", "postprocess_output_command", "cat", "cat"),
        ("use_dcc_output_checking", "dcc_output_checking", "0", False),
        ("colorise_output", "colorize_output", "0", False),
    ],
)
def test_alias_sets_the_real_parameter(alias, parameter, value, expected):
    assert (
        single_test(f"files=a.c\nt command=./a {alias}={value}\n")[parameter]
        == expected
    )


@pytest.mark.parametrize(
    "alias,parameter",
    [
        ("no_reproduce_command", "show_reproduce_command"),
        ("no_expected_output", "show_expected_output"),
        ("no_actual_output", "show_actual_output"),
        ("no_diff", "show_diff"),
    ],
)
def test_negated_alias_sets_the_opposite_of_its_boolean_value(alias, parameter):
    assert single_test(f"files=a.c\nt command=./a {alias}=1\n")[parameter] is False
    assert single_test(f"files=a.c\nt command=./a {alias}=no\n")[parameter] is True


# type coercion, defaults and required parameters


def test_values_are_coerced_to_the_parameters_type():
    t = single_test(
        "files=a.c\nt command=./a max_cpu_seconds='10' colorize_output=no optional_files=extra.h max_real_seconds=5\n"
    )
    assert t["max_cpu_seconds"] == 10
    assert t["colorize_output"] is False
    assert t["optional_files"] == ["extra.h"]
    assert t["max_real_seconds"] == 5
    assert t["files"] == ["a.c"]


def test_max_real_seconds_defaults_to_twenty_times_max_cpu_seconds():
    assert (
        single_test("files=a.c\nt command=./a max_cpu_seconds=3\n")["max_real_seconds"]
        == 60
    )


@pytest.mark.parametrize("value", ["1.5", "abc", "[1]"])
def test_non_integer_for_an_int_parameter_is_an_error_naming_it(value):
    assert parse_error(f"files=a.c\nt command=./a max_cpu_seconds={value}\n") == (
        f"<string>:2: error invalid value for parameter 'max_cpu_seconds': {value}"
    )


def test_ignore_characters_adds_whitespace_when_ignoring_whitespace_but_never_newline():
    t = single_test(
        "files=a.c\nt command=./a ignore_whitespace=1 ignore_characters=ab\n"
    )
    assert set(t["ignore_characters"]) == set("ab \t\r\x0b\x0c")
    t = single_test("files=a.c\nt command=./a ignore_characters='a\\nb'\n")
    assert set(t["ignore_characters"]) == set("ab")


def test_description_defaults_to_the_command_with_odd_words_quoted():
    assert (
        single_test("files=a.c\nt command=['./a', 'x y', 'é']\n")["description"]
        == "./a 'x y' 'é'"
    )
    assert (
        single_test("files=a.c\nt command='./a \"x y\"'\n")["description"]
        == "'./a \"x y\"'"
    )
    assert (
        single_test("files=a.c\nt command=./a description=custom\n")["description"]
        == "custom"
    )


def test_upload_fields_are_stringified_and_must_be_a_dict():
    assert single_test("files=a.c\nt command=./a upload_fields={'a': 1}\n")[
        "upload_fields"
    ] == {"a": "1"}
    assert parse_error("files=a.c\nt command=./a upload_fields=x\n") == (
        "<string>:2: invalid value for parameter 'upload_fields': x"
    )


def test_missing_program_is_an_error():
    assert (
        parse_error("program=''\nt\n")
        == "<string>:2: required parameter 'program' not specified"
    )


def test_missing_files_is_an_error():
    assert (
        parse_error("t files=[] program=x\n")
        == "<string>:1: required parameter 'files' not specified"
    )


def test_empty_command_list_is_an_error_naming_the_parameter():
    assert "'command'" in parse_error("t command=[]\n")


@pytest.mark.parametrize(
    "name,valid",
    [
        ("max_cpu_seconds", True),
        ("cpu", True),
        ("no_diff", True),
        ("label", True),
        ("_private", True),
        ("_", True),
        ("__dunder", False),
        ("nope", False),
    ],
)
def test_check_valid_parameter_name(name, valid):
    assert check_valid_parameter_name(name) is valid


# sandbox and parallelism


@pytest.mark.parametrize("value,expected", [("3", 3), (2.7, 2), (True, 1)])
def test_finalize_parallel_tests_gives_a_positive_int(value, expected):
    assert finalize_parallel_tests("parallel_tests", value, {}) == expected


@pytest.mark.parametrize("value", ["0", 0, -3])
def test_parallel_tests_zero_or_negative_means_one_per_cpu(value):
    assert finalize_parallel_tests("parallel_tests", value, {}) == (os.cpu_count() or 1)


def test_parallel_tests_falls_back_to_one_when_cpu_count_is_unknown(monkeypatch):
    monkeypatch.setattr(pd.os, "cpu_count", lambda: None)
    assert finalize_parallel_tests("parallel_tests", 0, {}) == 1


@pytest.mark.parametrize("value", ["abc", None, [1]])
def test_invalid_parallel_tests_is_an_error_naming_the_parameter(value):
    with pytest.raises(
        SpecificationError, match="invalid value for parameter 'parallel_tests'"
    ):
        finalize_parallel_tests("parallel_tests", value, {})


def test_a_compiler_ending_in_a_space_does_not_produce_a_double_space():
    """
    Specifications written before autotest supplied the separator often end
    the compiler with a space of their own; 42 of the COMP1521 26T2
    activities do.  The command a student is shown must not have a gap in it.
    """
    tests, _globals = parse_string(
        "files=a.c\n"
        'compiler_args=["main.c", "a.c", "-o", "a"]\n'
        'compilers=["gcc -Wall "]\n'
        '1 expected_stdout="x"\n',
        initial_parameters={"supplied_files_directory": "."},
    )
    assert tests["1"]["compile_commands"] == ["gcc -Wall main.c a.c -o a"]


def test_dcc_output_checking_is_off_when_marking():
    """
    dcc compares the output itself, so autotest hands it the answer in
    DCC_EXPECTED_STDOUT -- and the program being tested reads its own
    environment. Four lines of C which print it pass every test.

    Nothing can hide it from a student running the exercise on their own
    account. Marking is the one configuration where it can be kept back.
    """
    enabled, variables = dcc("files=a.c\nt command=./a expected_stdout=hi\n")
    assert enabled is True
    assert variables["DCC_EXPECTED_STDOUT"] == "hi"

    enabled, variables = dcc("marking=1\nfiles=a.c\nt command=./a expected_stdout=hi\n")
    assert enabled is False
    assert variables == {}


def test_a_marking_specification_can_ask_for_dcc_output_checking_anyway():
    """Off by default, not forbidden."""
    enabled, _variables = dcc(
        "marking=1\nfiles=a.c\nt command=./a expected_stdout=hi dcc_output_checking=1\n"
    )
    assert enabled is True
