name: type_checks
on: 
  push:
    branches: [ main ]
    paths:
        - '*.py'
  pull_request:
    branches: [ main ]
    paths:
        - '*.py'

jobs:
  do-type-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requests
        run: pip install types-requests

      - name: Install mypy
        run: pip install mypy

      - name: Install dependencies
        run: | 
          python3 -m pip install pipenv
          pipenv install

      - name: Install termcolor types
        run: python3 -m pip install types-termcolor

      - name: Run mypy 
        run: pipenv run mypy --namespace-packages --explicit-package-bases *.py